### PR TITLE
Time view

### PR DESCRIPTION
**Pull request by PhyllisWong**
Clicking on a date sends user to a view with times to select.

### CODE REVIEW

**Comment by pomfy113** [comment]
- The dashboard no longer resizes.
- The topbar is lower than usual now. If this is intentional, ignore this comment.
- For the timeview, the <p>s inside the bubbles appear to have a top margin and is not centered.

**Comment by pomfy113** [comment]
- Missing ending parenthesis on line 23 of Day.js
- Double checking, when you click it, is it meant to look this?
screen shot 2018-10-18 at 11 16 21 am

**Comment by PhyllisWong** [comment]
Fix the view issue. It was related to having to open PRs. 
Now that everything has been merged correctly the view should look as expected. 
WIP: back button still needs to change the state of the dashboard.
Will tackle after lunch.

**Comment by pomfy113** [comment]
Everything working as intended, though the ::hover effect is gone on dashboard and in smaller screen sizes, it can look like:
screen shot 2018-10-18 at 12 09 27 pm

This branch deals explicitly with the time view, so I'm approving this request. But it's something to look at later.

**Pull request merged**
